---
FTP:
  label: FTP
  description: You've found the FTP service open and need to know what you can do with it.

SMB:
  label: SMB
  description: You've found the SMB service open and need to know what you can do with it.

NFS:
  label: NFS
  description: You've found the NFS service open and need to know what you can do with it.

DNS:
  label: DNS
  description: You've found the DNS service open and need to know what you can do with it.

SMTP:
  label: SMTP
  description: You've found the SMTP service open and need to know what you can do with it.

IMAP:
  label: IMAP
  description: You've found the IMAP/IMAPS service open and need to know what you can do with it.

POP3:
  label: POP3
  description: You've found the POP3/POP3S service open and need to know what you can do with it.

SNMP:
  label: SNMP
  description: You've found the SNMP service open and need to know what you can do with it.

MySQL:
  label: MySQL
  description: You've found the MySQL service open and need to know what you can do with it.

MSSQL:
  label: MSSQL
  description: You've found the MSSQL service open and need to know what you can do with it.

IPMI:
  label: IPMI
  description: You've found the IPMI service open and need to know what you can do with it.

SSH:
  label: SSH
  description: You've found the SSH service open and need to know what you can do with it.

RDP:
  label: RDP
  description: You've found the RDP service open and need to know what you can do with it.

WinRM:
  label: WinRM
  description: You've found the WinRM service open and need to know what you can do with it.

WMI:
  label: WMI
  description: You've found the Windows Management Intstrumentation (WMI) service open and need to know what you can do with it.

TNS:
  label: TNS
  description: You've found the Oracle TNS service open and need to know what you can do with it.

Web:
  label: Web
  description: You've found the HTTP/HTTPS service open and need to know what you can do with it.

LDAP:
  label: LDAP
  description: You've found the LDAP service open and need to know what you can do with it.

DCOM:
  label: DCOM
  description: You've found the DCOM service open and need to know what you can do with it.

Kerberos:
  label: Kerberos
  description: You've found the Kerberos service open and need to know what you can do with it.

NTLM:
  label: NTLM
  description: Commands related to the NTLM protocol.

DNS:
  label: DNS
  description: Commands related to the DNS service.
